// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGE7aJsfsKzgHaKe_EySaZaVGAOIw76Mk',
    appId: '1:304128984508:web:93335ee37e4be76ef197b9',
    messagingSenderId: '304128984508',
    projectId: 'ehrspro',
    authDomain: 'ehrspro.firebaseapp.com',
    storageBucket: 'ehrspro.appspot.com',
    measurementId: 'G-FGLFV7WFG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuogX1niyjArQX_7GlHBZZv2S27PHtDEU',
    appId: '1:304128984508:android:676df224d53caa6bf197b9',
    messagingSenderId: '304128984508',
    projectId: 'ehrspro',
    storageBucket: 'ehrspro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhWtdFzI9tQAMxGfpXYs-Je71OA4tKY8',
    appId: '1:304128984508:ios:fb65c2ef58569d44f197b9',
    messagingSenderId: '304128984508',
    projectId: 'ehrspro',
    storageBucket: 'ehrspro.appspot.com',
    iosBundleId: 'com.example.healthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFhWtdFzI9tQAMxGfpXYs-Je71OA4tKY8',
    appId: '1:304128984508:ios:d72198f9a2d24467f197b9',
    messagingSenderId: '304128984508',
    projectId: 'ehrspro',
    storageBucket: 'ehrspro.appspot.com',
    iosBundleId: 'com.example.healthy.RunnerTests',
  );
}
